### ISSUE TITLE
Hugging Face repo uploads are being done massively

### ISSUE THREAD

**Issue by LysandreJik** [FLock-io/testnet-training-node-quickstart#19]
Hey! Lysandre from Hugging Face here.

We've been seeing some massive LoRA uploads recently (something like 20k over the past few days), and we've traced it back to this:

https://github.com/FLock-io/testnet-training-node-quickstart/blame/a55e04c11dffaffc7892af05d589f9a393e6650a/full_automation.py#L63-L72

It seems like several users are running this script, which, in a for loop, creates repos and pushes weights to them.
We would heavily recommend pushing to a single repo: we're using git so every update will be added as a new commit, so every model version will still be accessible.

We were about to bulk delete the repos as we saw it as spam initially, but we see it comes from here; do you mind updating your script so as to not bulk-create the repos, but rather push to a single repos with relevant commit names? 

Maybe cc @nickcom007 as you seem to be the author of the files!

Thanks for using HF :hugs:

**Comment by nickcom007** [comment]
Hey @LysandreJik , sorry for this. Our community is uploading a lot of repos because they are trying out different hyper-params. I will modify the script this week so that moving forward it will create a new commit instead of creating a new repo for each set of hyper-param tried.

**Comment by LysandreJik** [comment]
Thank you @nickcom007, we appreciate it!

**Comment by nickcom007** [comment]
https://github.com/FLock-io/testnet-training-node-quickstart/commit/79c8c263bcefcac5611576c850c0ab1957c2f071

Moving forward, for each competition, people will only have one repo for one base model they've tried. Hyper-param/ training data tuning will only create a new commit instead of new repo. Will this resolve the issue? @LysandreJik
